/**
 * Lista curada de dominios de correo temporal/desechable conocidos. El CRM viejo usaba la
 * lista completa de github.com/disposable/disposable-email-domains (~100k dominios, ~1.2 MB),
 * demasiado pesada para el bundle del Worker. Aquí va solo un subconjunto de los proveedores
 * más comunes: basta para el propósito (MARCAR con 🚩, nunca bloquear).
 */
export const DOMINIOS_DESECHABLES: ReadonlySet<string> = new Set([
  '0-mail.com',
  '10minutemail.com',
  '10minutemail.net',
  '20minutemail.com',
  '33mail.com',
  'anonaddy.com',
  'anonaddy.me',
  'burnermail.io',
  'cock.li',
  'dispostable.com',
  'dropmail.me',
  'emailondeck.com',
  'fakeinbox.com',
  'fakemail.net',
  'getairmail.com',
  'getnada.com',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'harakirimail.com',
  'inboxbear.com',
  'inboxkitten.com',
  'incognitomail.com',
  'jetable.org',
  'mailcatch.com',
  'maildrop.cc',
  'mailexpire.com',
  'mailforspam.com',
  'mailinator.com',
  'mailinator.net',
  'mailnesia.com',
  'mailnull.com',
  'mailsac.com',
  'mailtemp.info',
  'mintemail.com',
  'moakt.com',
  'mohmal.com',
  'mytemp.email',
  'nada.email',
  'nowmymail.com',
  'objectmail.com',
  'oneoffemail.com',
  'owlymail.com',
  'pokemail.net',
  'rmqkr.net',
  'sharklasers.com',
  'spam4.me',
  'spambog.com',
  'spamgourmet.com',
  'sroff.com',
  'temp-mail.io',
  'temp-mail.org',
  'tempail.com',
  'tempinbox.com',
  'tempmail.com',
  'tempmail.email',
  'tempmail.plus',
  'tempmailo.com',
  'tempr.email',
  'throwawaymail.com',
  'tmail.ws',
  'tmailor.com',
  'trashmail.com',
  'trashmail.de',
  'trashmail.net',
  'trbvm.com',
  'wegwerfmail.de',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
]);

/** ¿El dominio del correo es de un servicio de correo temporal/desechable conocido? */
export function esCorreoDesechable(email: string): boolean {
  const dominio = email.trim().toLowerCase().split('@').pop() ?? '';
  return DOMINIOS_DESECHABLES.has(dominio);
}
